services:
  pythonapp:
    build: './python/'
    command: sh -c "sleep 60s ; python3 ./main.py"
    depends_on:
      - db
    ports:
      - '3334:3334'

  db:
    build: './db/'
    container_name: 'db'
    restart: 'always'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3333:3306'